### ISSUE TITLE
Better errors for deploy.config.js

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#63]
Today I somehow ended up a repo without the `deploy.config.example.js` in it. So I just copied in my `deploy.config.js` and then ran `npm install` and got the below error. Seems like it shouldn't fail to install if the example file is missing but the real one is present.

```
Error: ENOENT: no such file or directory, rename './.deploy.config.example.js' -> './.deploy.config.js'
    at Object.fs.renameSync (fs.js:773:18)
    at Object.<anonymous> (/Users/drew/Local Sites/bernards/app/public/wp-content/themes/bernards2018/bin/vp-instal
l.js:6:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by SaFrMo** [comment]
Fixed in 1ad0484
