### ISSUE TITLE
CRITICAL Deploy error

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#87]
I tried to deploy a site today, and the site would just load blank with a `TypeError: n is not a function`. I tried `npm update` and then `npm install` and got this error. I think it relates to `.deploy.config.example.js` in some way.

```
Preparing Vuepress...
fs.js:773
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename './.deploy.config.example.js' -> './.deploy.config.js'
    at Object.fs.renameSync (fs.js:773:18)
    at Object.<anonymous> (/Users/drew/Local Sites/bernards/app/public/wp-content/themes/bernards2018/bin/vp-install.js:6:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)

    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepress@1.1.4 install: `node bin/vp-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuepress@1.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by drewbaker** [comment]
Running `npm run build` would also seem to work, but I'd get the same `TypeError: n is not a function` and nothing displaying in the browser.

**Comment by jrobson153** [comment]
This is fixed in the latest version. Just remove the “-p” from the “build” command in package.json

**Comment by drewbaker** [comment]
That did it. Thanks John! Saved me.
